# -*- coding: utf-8 -*-
"""function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Vu5KZ-hz-XFCSRQ4fVLORr2acKieLVO
"""

def cal_sum(a,b):
  sum=a+b
  print(sum)
  return sum
cal_sum(10,20)
cal_sum(100,200)
cal_sum(1000,2000)

def cal_multi(a,b):
  multi=a*b
  print(multi)
  return multi
cal_multi(2,4)
cal_multi(3,5)
cal_multi(4,6)

def hello():
  print("hello world!")

hello()

hello()

def cal_fac(n):
  fact=1
  for i in range(1, n+1):
    fact*=i
    print(fact)
cal_fac(5)

cal_fac(10)

# Student Grade Calculator using Functions in Python

def calculate_percentage(marks):
    """
    Function to calculate percentage
    """
    total = sum(marks)
    percentage = (total / (len(marks) * 100)) * 100
    return percentage

def get_grade(percentage):
    """
    Function to return grade based on percentage
    """
    if percentage >= 90:
        return "A+ 🎉"
    elif percentage >= 80:
        return "A"
    elif percentage >= 70:
        return "B"
    elif percentage >= 60:
        return "C"
    elif percentage >= 50:
        return "D"
    else:
        return "F ❌"

def main():
    print("=== Student Grade Calculator ===")
    subjects = int(input("Enter number of subjects: "))
    marks = []

    for i in range(subjects):
        score = float(input(f"Enter marks for subject {i+1} (out of 100): "))
        marks.append(score)

    percentage = calculate_percentage(marks)
    grade = get_grade(percentage)

    print(f"\nTotal Percentage: {percentage:.2f}%")
    print(f"Grade: {grade}")

# Run program
main()

# Simple Calculator using Functions in Python

def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b == 0:
        return "Error! Division by zero "
    return a / b

def main():
    print("=== Simple Calculator ===")
    print("Operations: +, -, *, /")

    while True:
        num1 = float(input("\nEnter first number: "))
        num2 = float(input("Enter second number: "))
        op = input("Enter operation (+ - * /): ")

        if op == "+":
            print("Result:", add(num1, num2))
        elif op == "-":
            print("Result:", subtract(num1, num2))
        elif op == "*":
            print("Result:", multiply(num1, num2))
        elif op == "/":
            print("Result:", divide(num1, num2))
        else:
            print("❌ Invalid operation!")

        choice = input("\nDo you want to continue? (yes/no): ").lower()
        if choice != "yes":
            print("Goodbye! 👋")
            break

# Run the calculator
main()

