# -*- coding: utf-8 -*-
"""linkedlist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T6MObxpsipD7W_AxuS-ccZKexZc7tfQ3
"""

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

# Creating linked list manually
head = Node("y")
head.next = Node("b")
head.next.next = Node("c")

# Traverse and print linked list
temp = head
while temp is not None:
    print(temp.data, end=" ")
    temp = temp.next

def fact(n):
    if n == 0:
        return 1
    return n * fact(n - 1)

print("The fact is", fact(7))

