# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zGyevqi6hTWIwZBdJziTkuSgarI_5W98
"""

a,b=0,1
while b<1000:
  print(b)
  a,b=b,a+b

for i in range(10):
  print(i)
  print("Yaqoob\n")

a=int(input("enter a number"))

a=int(input("enter a number"))
if a<12:
  print("number is less than 12")
else:
    print("number is greater than")

list=[1,2,3,4]
print(list)
print(type(list))

list.append(5)
print(list)

