# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c8dkcHMBCt-ryuZRDAGV9OhZB7L5T3n-

constant time O(1)
"""

def get_first_element(arr):
  return arr[2]
print(get_first_element([10, 20,30]))

"""linear time O(n)"""

def print_all_elements(arr):
    for item in arr:
        print(item)

print_all_elements([1, 2, 3, 4, 5])

"""Quadratic time O(n^2)"""

def print_pairf(arr):
  for i in arr:
    for j in arr:
      print(i, j)

print_pairf([1,2,3,4,5])

"""cube of O(n^3)

"""

def print_cube(arr):
  for i in arr:
    for j in arr:
      for k in arr:
        print(i, j,k)
print_cube([1,2,3])

